apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wiktorkowalski/k8s-hetzner.git  # UPDATE THIS
    targetRevision: master
    path: k8s/apps/tracing/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
