apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tempo
  namespace: tracing
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tempo.k8s.k8s.vicio.ovh`)  # UPDATE THIS
      kind: Rule
      services:
        - name: tempo
          port: 3100
  tls:
    certResolver: default
    domains:
      - main: tempo.k8s.k8s.vicio.ovh  # UPDATE THIS
