apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterissuer.yaml
  - certificate.yaml
  - argocd-cmd-params-cm.yaml
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  - ingress.yaml
