apiVersion: v1
kind: Secret
metadata:
  name: authentik
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: "JEqx/2IAeCOaL8Y3hEuFmjdamKLy6GqevvZmp4o01l6C4ACFEXLaKkCmZ8WwpSv9Ux8="
  AUTHENTIK_POSTGRESQL__HOST: "authentik-postgresql"
  AUTHENTIK_POSTGRESQL__NAME: "authentik"
  AUTHENTIK_POSTGRESQL__USER: "authentik"
  AUTHENTIK_POSTGRESQL__PASSWORD: "authentik-postgres-password"
