apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: opencost
  namespace: opencost
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`opencost.k8s.vicio.ovh`)
      kind: Rule
      services:
        - name: opencost
          port: 9090
  tls:
    certResolver: default
    domains:
      - main: opencost.k8s.vicio.ovh
